### PR TITLE
Token, CI and Documentation

### PR DESCRIPTION
**Pull request by carlocorradini**

### CODE REVIEW

**Comment by carlocorradini** [comment]
@gunar 
It's finally fixed!
I had a lot of headaches solving this, but it works now!
Moreover, when releasing a new version, I've added a step to check if `package.json` version matches the `git tag`.

**Comment by carlocorradini** [comment]
After this, I think we are ready to release`v2.0.0`.
Have you added `NPM_SECRET` to the Secret settings?

**Comment by gunar** [comment]
Cool. Yes I have.

**Comment by carlocorradini** [comment]
@gunar Awesome It works!

**Comment by gunar** [comment]
I jumped the gun. Anyway, the action failed:

https://github.com/gunar/shellcheck/actions/runs/3875109277/jobs/6607189661

**Comment by carlocorradini** [comment]
All fixed and ready in PR #43 
After merge you can tag, ...

**Pull request merged**
