### PR TITLE
chore: pre release v2.0.0

### PR DESCRIPTION
**Pull request by carlocorradini**

### CODE REVIEW

**Comment by carlocorradini** [comment]
Everything should work now 🥳

**Comment by gunar** [comment]
I've deleted and created a new `v2.0.0` tag but it seems like the action didn't run this time.

**Comment by carlocorradini** [comment]
@gunar 
```sh
git tag --delete v2.0.0 \
  && git push --delete origin v2.0.0 \
  && git tag v2.0.0 \
  && git push origin v2.0.0
```

**Comment by carlocorradini** [comment]
@gunar Any update?

**Pull request merged**
