### PR TITLE
fix: support decompress windows

### PR DESCRIPTION
**Pull request by carlocorradini**

### CODE REVIEW

**Comment by gunar** [comment]
Tests aren't passing

**Comment by carlocorradini** [comment]
Wait, I need to check

**Comment by carlocorradini** [comment]
I need to test it on Windows. I don't know it fails, maybe EOL?

**Comment by gunar** [comment]
Hah that is weird

**Comment by carlocorradini** [comment]
@gunar 
Finally, it's working for Windows, too.
The CI is failing because we are hitting the GitHub API call limit. When you read this message, please re-run the workflow, and it should succeed now.

**Comment by carlocorradini** [comment]
Again, API rate limits exceeded.
I've read [_Rate limits for requests from GitHub Actions_](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions) and [_Automatic token authentication_](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and it should work without any problem. Do you have any idea?

**Comment by carlocorradini** [comment]
@gunar Alleluia! It works!

**Pull request merged**
